# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTjCWrI4f7JaGhHXI3oA9OCQapjuNZh5
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler


def preprocess_data(df):

    """
    Preprocess Bitcoin dataset for machine learning.
    """

    # -----------------------------------
    # Convert Date Column
    # -----------------------------------
    df['Date'] = pd.to_datetime(df['Date'])

    # -----------------------------------
    # Sort Dataset by Date
    # -----------------------------------
    df = df.sort_values('Date')

    # Reset index
    df.reset_index(drop=True, inplace=True)

    # -----------------------------------
    # Feature Engineering
    # -----------------------------------

    # 7-Day Moving Average
    df['MA7'] = df['Close'].rolling(window=7).mean()

    # 30-Day Moving Average
    df['MA30'] = df['Close'].rolling(window=30).mean()

    # Daily Returns
    df['Returns'] = df['Close'].pct_change()

    # Lag Features
    df['Lag1'] = df['Close'].shift(1)

    df['Lag2'] = df['Close'].shift(2)

    df['Lag3'] = df['Close'].shift(3)

    # -----------------------------------
    # Handle Missing Values
    # -----------------------------------
    df.dropna(inplace=True)

    # -----------------------------------
    # Feature Selection
    # -----------------------------------
    features = [
        'Open',
        'High',
        'Low',
        'Volume',
        'MA7',
        'MA30',
        'Lag1',
        'Lag2',
        'Lag3'
    ]

    target = 'Close'

    # -----------------------------------
    # Create Feature Matrix and Target
    # -----------------------------------
    X = df[features]

    y = df[target]

    # -----------------------------------
    # Feature Scaling
    # -----------------------------------
    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    # -----------------------------------
    # Return Processed Data
    # -----------------------------------
    return X_scaled, y, scaler