# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTjCWrI4f7JaGhHXI3oA9OCQapjuNZh5
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

def clean_df(df):
    df = df.copy()

    df = df[df['Date'] != 'Date']
    df = df.reset_index(drop=True)

    df['Date'] = df['Date'].astype(str).str.strip()
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

    df = df.dropna(subset=['Date'])

    return df

def preprocess_data(df):
    df = df[df['Date'] != 'Date']
    df = df.reset_index(drop=True)

    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df = df.dropna(subset=['Date'])

    df['MA7'] = df['Close'].rolling(7).mean()
    df['MA14'] = df['Close'].rolling(14).mean()

    df['Lag1'] = df['Close'].shift(1)
    df['Lag2'] = df['Close'].shift(2)
    df['Lag3'] = df['Close'].shift(3)

    df = df.dropna()

    features = ['Open','High','Low','Volume','MA7','MA14','Lag1','Lag2','Lag3']

    scaler = StandardScaler()
    df[features] = scaler.fit_transform(df[features])

    return df, features

df = clean_df(df)
df_processed, features = preprocess_data(df)