# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xigkf-bNmofIba6SctZ6yIgFLU8QqKYb
"""

import pandas as pd
import joblib

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

def calculate_mae(y_true, y_pred):
    return mean_absolute_error(y_true, y_pred)

def calculate_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# 1. Load data
def load_data(path):
    df = pd.read_csv(path)
    return df


# 2. Prepare features
def prepare_data(df):
    features = [
        "Open", "High", "Low", "Volume",
        "MA7", "MA30",
        "Lag1", "Lag2", "Lag3",
        "Returns", "RSI"
    ]

    target = "Close"

    X = df[features]
    y = df[target]

    return X, y


# 3. Split data (time series)
def split_data(X, y):
    return train_test_split(
        X, y,
        test_size=0.2,
        shuffle=False
    )


# 4. Train model
def train_model(X_train, y_train):
    model = LinearRegression()
    model.fit(X_train, y_train)
    return model


# 5. Evaluate
def evaluate(model, X_test, y_test):
    preds = model.predict(X_test)

    mae = calculate_mae(y_test, preds)
    rmse = calculate_rmse(y_test, preds)

    return mae, rmse, preds


# 6. Save model
def save_model(model, path="model.pkl"):
    joblib.dump(model, path)


# 7. Main pipeline
def main():
    df = load_data("/content/processed_btc_data.csv")

    X, y = prepare_data(df)

    X_train, X_test, y_train, y_test = split_data(X, y)

    model = train_model(X_train, y_train)

    mae, rmse, preds = evaluate(model, X_test, y_test)

    print("MAE:", mae)
    print("RMSE:", rmse)

    save_model(model)


if __name__ == "__main__":
    main()