# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPxg8w2-ZwqslFdplny4TqX_vhTWIS-_
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

def calculate_mae(y_true, y_pred):
    return mean_absolute_error(y_true, y_pred)

def calculate_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))